### ISSUE TITLE
crashing upon lobby join[linux]

### ISSUE THREAD

**Issue by USMP-lancer** [MapleWheels/Barotrauma_HotkeyReload#14]
so im  getting a crash with the mod, im 99% sure its mod toolkit, as for somereason it doesnt crash teh first time i join a lobby, only the second time, when it doesnt crash it gives an error, saying it cannot find MonoGame.Framework.Windows.NetStandard(based on what its trying to find your versions only made to work with windows), if it were changed up a bit im sure it could work on linux as well as windows, but for now its only usable on windows systems

**Comment by USMP-lancer** [comment]
i feel its important to note that it DID work before adding the gui config and such

**Comment by MapleWheels** [comment]
For some reason, I never got an email notification about this error. Sorry for the delay.

This is caused by Modding Toolkit's config GUI relying on a MonoGame dll that is platform dependent. I need to have a separate Steam Workshop listing for a Linux version.
