### ISSUE TITLE
Inability to reload two weapons in hand at the same time, e.g. stun baton, revolver.

### ISSUE THREAD

**Issue by zhu-rengong** [MapleWheels/Barotrauma_HotkeyReload#9]

**Comment by MapleWheels** [comment]
I'll look into this shortly.

**Update**: Reloading both weapons works just fine. However, there is a bug where if two items are reloaded that use compatible ammunition, the ammunition from the first item in hand will be put into the second one and the first one will not be reloaded.

Double Reload Works Fine:
![image](https://user-images.githubusercontent.com/16272764/201781616-393e110f-746b-4d24-bc98-2ec602fbddc1.png)
![image](https://user-images.githubusercontent.com/16272764/201781643-5726bb49-61c3-4ae3-a090-d04303c72226.png)

However....
![image](https://user-images.githubusercontent.com/16272764/201781893-b66d8ee7-1c66-4f6c-b356-d29aa100f49f.png)

![image](https://user-images.githubusercontent.com/16272764/201781920-aefc8ab5-a781-4ee1-a025-8ff004fe3450.png)

**Comment by MapleWheels** [comment]
@zhu-rengong Is the above actually your issue or are you unable to reload a revolver and stun baton as per the title?

**Comment by MapleWheels** [comment]
Fixed the issue I described above on PR #11 . Merged into `dev` branch for next release.
